config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :toplics

  root 'doorplate#index'

end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, type: String
  field :body, type: String
  field :comments, type: Array
end

app/models/toplic.rb
class Toplic
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :linkwith, type: Object
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
     render "hello, world!"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    HEADING <= "Winda Tang's Kingdom"
    SUB_HEADING <= "WindaTang's Individual Website, design and developer by Winda"
    # if @description.nil?
    #   @description = "First WebSite";
    # end
    # if @keywords.nil?
    #   @description = "First WebSite";
    # end
    # render  'hello'
  end
  # def self_meta_tag (description = "The first Ruby Website")
  #   puts [
  #       tag('meta', :charset => 'utf-8'),
  #       tag('meta', :name => 'X-UA-Compatible', :content =>"IE=edge,chrome=1"),
  #       tag('meta', :name => 'description', :content => description),
  #       tag('meta', :name => 'viewport', :content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"),
  #       tag('meta', :name => 'author', :content => "Winda Tang")
  #   ].join("\n")
  #   alias self_meta_tag self_meta_tags
  # end
  # def init
  #
  # end
  if @description.nil?
    @description = "First WebSite";
  end
  if @keywords.nil?
    @description = "First WebSite";
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :comments)
    end
end

app/controllers/doorplate_controller.rb
class DoorplateController < ApplicationController
  def index
  end

end

app/controllers/toplics_controller.rb
class ToplicsController < ApplicationController
  before_action :set_toplic, only: [:show, :edit, :update, :destroy]

  # GET /toplics
  # GET /toplics.json
  def index
    @toplics = Toplic.all
  end

  # GET /toplics/1
  # GET /toplics/1.json
  def show
  end

  # GET /toplics/new
  def new
    @toplic = Toplic.new
  end

  # GET /toplics/1/edit
  def edit
  end

  # POST /toplics
  # POST /toplics.json
  def create
    @toplic = Toplic.new(toplic_params)

    respond_to do |format|
      if @toplic.save
        format.html { redirect_to @toplic, notice: 'Toplic was successfully created.' }
        format.json { render :show, status: :created, location: @toplic }
      else
        format.html { render :new }
        format.json { render json: @toplic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toplics/1
  # PATCH/PUT /toplics/1.json
  def update
    respond_to do |format|
      if @toplic.update(toplic_params)
        format.html { redirect_to @toplic, notice: 'Toplic was successfully updated.' }
        format.json { render :show, status: :ok, location: @toplic }
      else
        format.html { render :edit }
        format.json { render json: @toplic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toplics/1
  # DELETE /toplics/1.json
  def destroy
    @toplic.destroy
    respond_to do |format|
      format.html { redirect_to toplics_url, notice: 'Toplic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toplic
      @toplic = Toplic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toplic_params
      params.require(:toplic).permit(:title, :description, :linkwith)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/doorplate_helper.rb
module DoorplateHelper
end

app/helpers/toplics_helper.rb
module ToplicsHelper
end

app/views/application/index.html.slim
h1 index
p Find me in app/views/doorplate/index.html.slim

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_field :body
  .field
    = f.label :comments
    = f.text_field :comments
  .actions = f.submit 'Save'

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles

table
  thead
    tr
      th Title
      th Body
      th Comments
      th
      th
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = article.body
        td = article.comments
        td = link_to 'Show', article
        td = link_to 'Edit', edit_article_path(article)
        td = link_to 'Destroy', article, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Article', new_article_path

app/views/articles/new.html.slim
h1 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
p#notice = notice

p
  strong Title:
  = @article.title
p
  strong Body:
  = @article.body
p
  strong Comments:
  = @article.comments

= link_to 'Edit', edit_article_path(@article)
'|
= link_to 'Back', articles_path

app/views/doorplate/index.html.slim
h1 Doorplate#index
p Find me in app/views/doorplate/index.html.slim

app/views/layouts/_foot.html.slim
footer id="footer"
  .main
  /= render 'footer'
  /| Copyright © #{year} #{author}

app/views/layouts/_head.html.slim
head
  title FirstRuby
  - if !head.nil? && !head.title.empty?
    | {title}
  /meta name="keywords" content="template language"
  /meta name="author" content=author
  meta charset= "utf-8"
  meta name= "X-UA-Compatible"  content="IE=edge,chrome=1"
  meta name= "description"  content= @description
  meta name= "keywords"  content= @keywords
  meta name= "viewport"  content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
  meta name= "author"  content="Winda Tang"
  = csrf_meta_tags
  = stylesheet_link_tag  'application', :media => 'all', 'data-turbolinks-track' => true
  = javascript_include_tag "application", 'data-turbolinks-track' => true
  script src="require.js"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render partial:"layouts/head", object: @head  %>
<body>
  <div class="wrap">
    <header>
      <div class="main">
        <h1><%=HEADING %></h1>
        <h2><%=SUB_HEADING%></h2>
      </div>
    </header>
    <%= yield %>
    <%= render partial:"layouts/foot", object: @foot   %>
  </div>
</body>
</html>

app/views/toplics/_form.html.slim
= form_for @toplic do |f|
  - if @toplic.errors.any?
    #error_explanation
      h2 = "#{pluralize(@toplic.errors.count, "error")} prohibited this toplic from being saved:"
      ul
        - @toplic.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :linkwith
    = f.text_field :linkwith
  .actions = f.submit 'Save'

app/views/toplics/edit.html.slim
h1 Editing toplic

== render 'form'

= link_to 'Show', @toplic
'|
= link_to 'Back', toplics_path

app/views/toplics/index.html.slim
h1 Listing toplics

table
  thead
    tr
      th Title
      th Description
      th Linkwith
      th
      th
      th

  tbody
    - @toplics.each do |toplic|
      tr
        td = toplic.title
        td = toplic.description
        td = toplic.linkwith
        td = link_to 'Show', toplic
        td = link_to 'Edit', edit_toplic_path(toplic)
        td = link_to 'Destroy', toplic, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Toplic', new_toplic_path

app/views/toplics/new.html.slim
h1 New toplic

== render 'form'

= link_to 'Back', toplics_path

app/views/toplics/show.html.slim
p#notice = notice

p
  strong Title:
  = @toplic.title
p
  strong Description:
  = @toplic.description
p
  strong Linkwith:
  = @toplic.linkwith

= link_to 'Edit', edit_toplic_path(@toplic)
'|
= link_to 'Back', toplics_path